apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: web2
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: web2
  spec:
   containers:
    - image: "docker089/finalclient3"
      imagePullPolicy: Always
      name: web2
      ports:
       - containerPort: 80
