apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: songapi
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: songapi
  spec:
   containers:
    - image: "docker089/finalserver"
      imagePullPolicy: Always
      name: songapi
      ports:
       - containerPort: 80
